### ISSUE TITLE
SEO optimization and meta tags

### ISSUE THREAD

**Issue by kennstenicht** [kennstenicht/portfolio-frontend#18]
- [x] What is the best way to set meta tags?
- [ ] Sharing images
  - [ ] custom sharing image for project pages
  - [x] Fallback image
  - [ ] generating images?
- [x] structured data
  - [x] company information
  - [x] project?
- [x] fastboot
  - [x] fix ember-animated issue
