### ISSUE TITLE
mobiledoc editor

### ISSUE THREAD

**Issue by kennstenicht** [kennstenicht/portfolio-frontend#5]
- [x] install mobiledoc renderer and editor
- [x] create custom component wrapper for mobiledoc
- [ ] toolbar
  - [ ] style toolbar
  - [ ] display toolbar above selection #10
  - [ ] compact and full version #11
  - [ ] add seperate card toolbar #12
- [x] create atoms
  - [x] line break 
- [ ] create cards
  - [ ] image card #6
  - [ ] slider card #3 
  - [ ] embedding card #4
  - [ ] gallery card?
  - [ ] column card #7
  - [ ] video card #8
  - [ ] display custom component #9
